### PR TITLE
Upgrade tally to v4 (fixes uber-go/cadence-client#1157)

### PR DESCRIPTION
**Pull request by nkcmr**
**What changed?**
Upgrade of the `tally` library to v4.

**Why?**
Pre-v4 versions of tally used a non-official prometheus library (`github.com/m3db/prometheus_client_golang`) that causes integration issues with cadence users that need to feed cadence metrics into existing prometheus integrations that use the _actual_ prometheus client library.

Tally v4 corrects this issue by using the official prometheus library.

**How did you test it?**
This fork has been deployed to production systems at Cloudflare without much issue.

**Potential risks**
The tally v4 upgrade does not appear to actually have contained that many "breaking" changes/behaviors, it just unforked prometheus client library and switch to go modules (https://github.com/uber-go/tally/releases/tag/v4.0.0). Risk seems minimal.

### CODE REVIEW

**Comment by nkcmr** [comment]
Hey @vytautas-karpavicius, hate to bug you, but I saw you approving/commenting on other PRs and was hoping you could help. Is it possible to get some feedback on this PR from you or anyone on your team?

Worth noting that this fork is being used in our production systems without much issue if that helps. 🙂

Let me know if anything else is needed. Thanks so much.

**Review by vytautas-karpavicius — APPROVED** [review]

**Comment by vytautas-karpavicius** [comment]
> Hey @vytautas-karpavicius, hate to bug you, but I saw you approving/commenting on other PRs and was hoping you could help. Is it possible to get some feedback on this PR from you or anyone on your team?
> 
> Worth noting that this fork is being used in our production systems without much issue if that helps. 🙂
> 
> Let me know if anything else is needed. Thanks so much.

Thank you for the contribution!

**Comment by nkcmr** [comment]
@vytautas-karpavicius Thank _you_. Glad to help 😄

**Comment by Groxx** [comment]
hm :\  I'm not sure we can keep this, it's a breaking change since we expose tally.Scope in a number of locations in our API.

**Pull request merged**
